baseURL = "http://wellarchitected.workshop.kr.s3-website-us-west-2.amazonaws.com/"
languageCode = "en-US"
title = "AWS Well-Architected Labs"
theme = "learn"
defaultContentLanguage = "en"

[params]
    themeVariant = "walabs"
    disableShortcutsTitle = true

    # Order sections in menu by "weight" or "title". Default to "weight"
    ordersectionsby = "weight"
        # Weights by pillar:
        # 1000 - Operational Excellence
        # 2000 - Security
        # 3000 - Reliability
        # 4000 - Performance Efficiency
        # 5000 - Cost Optimization
        # 6000 - Well Architected Tool
    editURL = "https://github.com/sykang169/aws-well-architected-labs-kor/"
    description = "Hands on labs and real world design scenarios for Well-Architected workloads"
    author = "Seyong Kang"
    showVisitedLinks = true
    # Hide Next and Previous page buttons normally displayed full height beside content
    disableNextPrev = false
    #AWS custom params
    base_github_url = "https://github.com/sykang169/aws-well-architected-labs-kor"
    base_raw_github_url = "https://raw.githubusercontent.com/awslabs/aws-well-architected-labs/master/"
    #{{% siteparam "base_github_url" %}}

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> AWS Homepage"
  url = "https://aws.amazon.com/"
  weight = 1000

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> AWS Well-Architected Framework"
  url = "https://aws.amazon.com/architecture/well-architected/?nc1=h_ls&wa-lens-whitepapers.sort-by=item.additionalFields.sortDate&wa-lens-whitepapers.sort-order=desc"
  weight = 1000

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]


[deployment]
  [[deployment.targets]]
    name = "s3"
    URL = "s3://wellarchitected.workshop.kr/"


[Languages]
    [Languages.en]
        weight = 1
        languageName = "English"

    [Languages.ko]
        weight = 2
        languageName = "한국어"

    # Menu shortcuts on left side

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Amazon Free Tier"
url = "https://aws.amazon.com/free/"
weight = 10
